### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by yakir12** [abelsiqueira/jill#25]
I'm on a headless Raspbian on a Raspberry Pi (4), and:
```bash
$ bash -ci "$(curl -fsSL https://raw.githubusercontent.com/abelsiqueira/jill/master/jill.sh)"
JILL - Julia Installer 4 Linux (and MacOS) - Light
Copyright (C) 2017 Abel Soares Siqueira <abel.s.siqueira@gmail.com>
Distributed under terms of the GPLv3 license.
This script will:

  - Download latest stable Julia
  - Create a link for julia
  - Create a link for julia-VER

Download folder: /home/pi/packages/julias
Link folder: /home/pi/.local/bin

Download folder will be created if required
Do you accept these terms? (Y/N) y
--2020-02-20 07:55:37--  https://julialang.org/downloads/
Resolving julialang.org (julialang.org)... 151.101.130.49, 151.101.2.49, 151.101.194.49, ...
Connecting to julialang.org (julialang.org)|151.101.130.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24270 (24K) [text/html]
Saving to: 'page.html'

page.html                                            100%[=====================================================================================================================>]  23.70K  --.-KB/s    in 0.009s  

2020-02-20 07:55:37 (2.63 MB/s) - 'page.html' saved [24270/24270]

Downloading Julia version 1.3.1
--2020-02-20 07:55:37--  https://julialang-s3.julialang.org/bin/linux/x32/1.3/julia-1.3.1-linux-armv7l.tar.gz
Resolving julialang-s3.julialang.org (julialang-s3.julialang.org)... 151.101.86.49, 2a04:4e42:14::561
Connecting to julialang-s3.julialang.org (julialang-s3.julialang.org)|151.101.86.49|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-20 07:55:37 ERROR 404: Not Found.


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I should mention that manually downloading (`wget [link]`), unpacking (`tar -zxvf [julia.tar.gz]`), and testing (`julia`) worked just fine.

**Comment by johnnychen94** [comment]
Yeah, actually this script hardcoded the platform to x-bits

```diff
-https://julialang-s3.julialang.org/bin/linux/x32/1.3/julia-1.3.1-linux-armv7l.tar.gz
+https://julialang-s3.julialang.org/bin/linux/armv7l/1.3/julia-1.3.1-linux-armv7l.tar.gz
```

If you allow python installed, you can try my new fork :P https://github.com/johnnychen94/jill.py

**Comment by yakir12** [comment]
Tried it and it ~~worked perfectly~~ (I already had python3 installed on the system). Oops, spoke too soon, it had an `FileNotFoundError`. See below:

```
pi@raspberrypi:~ $ pip3 install jill --user -U
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting jill
  Downloading https://files.pythonhosted.org/packages/3a/02/9659e1ac6f4a751c855bdc35ac15c0b282265a3c40dc6c2b45d773743175/jill-0.6.4-py3-none-any.whl
Collecting semantic-version (from jill)
  Downloading https://files.pythonhosted.org/packages/ba/00/098b5c385c3cf8f1ff4d9b909623859de4eb95c115aed81263a4e3b84ea3/semantic_version-2.8.4-py2.py3-none-any.whl
Collecting wget (from jill)
  Downloading https://www.piwheels.org/simple/wget/wget-3.2-py3-none-any.whl
Collecting fire (from jill)
  Downloading https://files.pythonhosted.org/packages/d9/69/faeaae8687f4de0f5973694d02e9d6c3eb827636a009157352d98de1129e/fire-0.2.1.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 2.7MB/s 
Collecting python-gnupg (from jill)
  Downloading https://files.pythonhosted.org/packages/04/e8/05fd06574b99639b87e1835a46ffb253974dc31256fd18d127c01ce8e2f2/python_gnupg-0.4.5-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from jill) (2.21.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from fire->jill) (1.12.0)
Collecting termcolor (from fire->jill)
  Downloading https://www.piwheels.org/simple/termcolor/termcolor-1.1.0-py3-none-any.whl
Building wheels for collected packages: fire
  Running setup.py bdist_wheel for fire ... done
  Stored in directory: /home/pi/.cache/pip/wheels/31/9c/c0/07b6dc7faf1844bb4688f46b569efe6cafaa2179c95db821da
Successfully built fire
Installing collected packages: semantic-version, wget, termcolor, fire, python-gnupg, jill
  Installing from a newer Wheel-Version (1.1)
Successfully installed fire-0.2.1 jill-0.6.4 python-gnupg-0.4.5 semantic-version-2.8.4 termcolor-1.1.0 wget-3.2
pi@raspberrypi:~ $ jill install
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

jill will:
  1) install Julia latest stable release for linux-ARMv7 into /home/pi/packages/julias
  2) make symlinks in /home/pi/.local/bin
  3) add /home/pi/.local/bin to PATH if necessary
Continue installation? [Y/n] y
----- Download Package -----
update is disabled for tier-2 support ARMv7
downloading Julia release for 1.3.1-linux-ARMv7
downloading from https://julialang-s3.julialang.org/bin/linux/armv7l/1.3/julia-1.3.1-linux-armv7l.tar.gz
100% [........................................................................] 84910930 / 84910930
finished downloading julia-1.3.1-linux-armv7l.tar.gz
downloading from https://julialang-s3.julialang.org/bin/linux/armv7l/1.3/julia-1.3.1-linux-armv7l.tar.gz.asc
100% [..................................................................................] 866 / 866
finished downloading julia-1.3.1-linux-armv7l.tar.gz.asc
verifying 1.3.1-linux-ARMv7 succeed
----- Install Julia -----
install Julia to /home/pi/packages/julias/julia-1.3
make symlink /home/pi/.local/bin/julia-1
Traceback (most recent call last):
  File "/home/pi/.local/bin/jill", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/jill/__main__.py", line 21, in main
    }, name="jill")
  File "/home/pi/.local/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/pi/.local/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/pi/.local/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/jill/install.py", line 341, in install_julia
    installer(package_path, install_dir, symlink_dir, version, upgrade)
  File "/home/pi/.local/lib/python3.7/site-packages/jill/install.py", line 182, in install_julia_linux
    make_symlinks(bin_path, symlink_dir, version)
  File "/home/pi/.local/lib/python3.7/site-packages/jill/install.py", line 126, in make_symlinks
    old_ver = get_exec_version(linkpath)
  File "/home/pi/.local/lib/python3.7/site-packages/jill/install.py", line 52, in get_exec_version
    version = subprocess.check_output(ver_cmd).decode("utf-8")
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.local/bin/julia-1.3': '/home/pi/.local/bin/julia-1.3'
```

**Comment by johnnychen94** [comment]
Thanks for trying! Fixed in jill.py v0.6.5.

**Comment by yakir12** [comment]
Can confirm.

**Comment by RaviPadma-star** [comment]
root@appTomcat:~# cd /opt
root@appTomcat:/opt# sudo wget https://downloads.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
--2022-12-05 13:50:36--  https://downloads.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
Resolving downloads.apache.org (downloads.apache.org)... 88.99.95.219, 135.181.214.104, 2a01:4f9:3a:2c57::2, ...
Connecting to downloads.apache.org (downloads.apache.org)|88.99.95.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-05 13:50:36 ERROR 404: Not Found.

root@appTomcat:/opt#

guys anyone help pls i am not able to download any package from server via git-bash
